services:
  oracle-db:
    image: gvenzl/oracle-free
    env_file: ./.env
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_DATABASE: $ORACLEDB_DATABASE
      ORACLE_PASSWORD: $ORACLEDB_ROOT_PASSWORD
      APP_USER: $ORACLEDB_USER
      APP_USER_PASSWORD: $ORACLEDB_ROOT_PASSWORD
  backend:
    restart:
      unless-stopped
    depends_on:
      - oracle-db
    build: ./backEnd
    container_name: backEnd
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:oracle:thin:@oracle-db:1521/$ORACLEDB_DATABASE",
          "spring.datasource.username": "$ORACLEDB_USER",
          "spring.datasource.password": "$ORACLEDB_ROOT_PASSWORD"
        }
    stdin_open: true
    tty: true
  swing-ui:
    build: ./swing-ui # Path to your Swing UI Dockerfile
    container_name: swing-ui
    depends_on:
      - backend
    environment:
      BACKEND_API_URL: "http://backend:8080"
      DISPLAY: "host.docker.internal:0.0" # Set DISPLAY variable for X11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket for communication
    stdin_open: true
    tty: true
